[package]
name = "nintendo-64-emulator"
version = "1.0.0"
edition = "2021"

[dependencies]
glfw = "0.49.0"
gl = "0.14.0"
nalgebra = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rodio = "0.14.0"

[profile.release]
opt-level = 3